### ISSUE TITLE
how to create coverage file 

### ISSUE THREAD

**Issue by stroke1989** [genepattern/MutSigCV#2]
Excuse me:
  I am trying to used MutSigCV to analyze my own WES data. Several input files were required, including MAF file, coverage file and one covariate file. Although the document provided one alternative coverage file, a coverage file created from my own data may generate more accurate results. The document pointed out that  this tab-delimited file can be produced by processing the sample-level coverage files in WIG (wiggle) format output by the MuTect tool.  But no more details, could you provide more details about how to create specific coverage file. A example will be the best. Hope your response! Appreciate!

**Comment by bahill** [comment]
Hello,
Detailed information about the coverage file and MuTect (not produced or maintained by our team) is available further down in the documentation for MutSigCV
https://www.genepattern.org/modules/docs/MutSigCV/1#input_files
